from typing import List

from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()
from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langchain_tavily import TavilySearch

# define a class to inherit from BaseModel
class Source(BaseModel):
    """
        Schema for a source used by the agent.
    """
    url:str = Field(description="The URL of the source")

# nested field in another pydantic class
class AgentResponse(BaseModel):
    """
        Schema for the agent response with answers and sources.
    """
    answer:str = Field(description="The answer generated by the agent")
    sources:List[Source] = Field(default_factory= list, description="List of sources used to generate the answer.")


# creating the agent
llm = ChatOpenAI(model="gpt-5")
tools = [TavilySearch()]
agent = create_agent(model=llm, tools=tools, response_format=AgentResponse)

def main():
    print("Hello from react-agent!")
    result = agent.invoke(
        {
            "messages":HumanMessage(
                content="Search in linkeding 3 internships in Ontario that requires knowledge about LLM and langchain"
                )
        }
    )
    print(result)
if __name__ == "__main__":
    main()
